<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <Reference Include="SpiritReforged">
	    <HintPath>..\SpiritReforged\bin\Debug\net8.0\SpiritReforged.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<!-- References -->

</Project>